apiVersion: apps/v1
kind: Deployment
metadata:
  name: salon-booking
  labels:
    app: salon-booking
    component: backend
spec:
  replicas: 3  # 3 réplicas para alta disponibilidade
  selector:
    matchLabels:
      app: salon-booking
  template:
    metadata:
      labels:
        app: salon-booking
        component: backend
    spec:
      containers:
      - name: salon-booking
        image: miapferreira/salon-booking:latest
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: PORT
          value: "3000"
        - name: DB_HOST
          valueFrom:
            configMapKeyRef:
              name: salon-booking-config
              key: db-host
        - name: DB_PORT
          valueFrom:
            configMapKeyRef:
              name: salon-booking-config
              key: db-port
        - name: DB_NAME
          valueFrom:
            configMapKeyRef:
              name: salon-booking-config
              key: db-name
        - name: DB_USER
          valueFrom:
            secretKeyRef:
              name: salon-booking-secrets
              key: db-user
        - name: DB_PASSWORD
          valueFrom:
            secretKeyRef:
              name: salon-booking-secrets
              key: db-password
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /api/health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
        # Configurações de segurança
        securityContext:
          runAsNonRoot: true
          runAsUser: 1001
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities:
            drop:
            - ALL
